/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.action;

import ict.ocrabase.main.java.client.webinterface.TaskManager;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.hbase.MasterNotRunningException;
import org.apache.hadoop.hbase.ZooKeeperConnectionException;
import org.apache.hadoop.hbase.master.HMaster;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ocrabaseadmin.operation.authorityOperation;
import com.ocrabaseadmin.operation.tableOperation;
import com.ocrabaseadmin.struts.form.AddColumnForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-24-2011
 * 
 * XDoclet definition:
 * @struts.action path="/addColumn" name="addColumnForm" input="/viewDescriptor.jsp" scope="request" validate="true"
 */
public class AddColumnAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddColumnForm addColumnForm = (AddColumnForm) form;// TODO Auto-generated method stub
		
		HMaster master = (HMaster)getServlet().getServletContext().getAttribute(HMaster.MASTER);
		
		tableOperation to = new tableOperation();
		
		String tableName = (String)addColumnForm.getNewTableName();
		List<HashMap<String,Object>> columnFamily = new LinkedList<HashMap<String,Object>>();
		
		//authority
		Configuration conf = master.getConfiguration();
		boolean security = conf.getBoolean("hbase.server.security",false);
		if(security) {
			String username = (String)request.getSession().getAttribute("username");
			String usertype = (String)request.getSession().getAttribute("usertype");
			
			if(usertype.equals("user")) {
				authorityOperation ao = new authorityOperation();
				try {
					if(!ao.validateUserOperation(master, tableName, ao.getUserTypeForTable(master, username, tableName), true)) {
						PrintWriter out = response.getWriter();
						out.println("<script>");
						out.println("alert(\"You Have No Access.\");");
						out.println("window.location=\"/viewTableList.do\";");
						out.println("</script>");
						
						return null;
					}
				} catch (MasterNotRunningException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ZooKeeperConnectionException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}
		if(TaskManager.isActive(tableName)) {
			PrintWriter out;
			try {
				out = response.getWriter();
				
				out.println("<script>");
				out.println("alert(\"The Table is Locked.\");");
				out.println("window.location=\"/viewTableList.do\";");
				out.println("</script>");
				
				return null;
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		//authority
		
		for(int i = 1; ;i++) {
			if(addColumnForm.getFamilyName("familyName_" + i) == null) {
				break;
			}
			else {
				HashMap<String,Object> hm = new HashMap<String,Object>();
				hm.put("familyName", addColumnForm.getFamilyName("familyName_" + i));
				hm.put("versions", addColumnForm.getVersions("versions_" + i));
				hm.put("compression", addColumnForm.getCompression("compression_" + i));
				
				//System.out.println(createTableForm.getCompression("compression_" + i));
				
				hm.put("inMemory", addColumnForm.getInMemory("inMemory_" + i));
				hm.put("blockCache", addColumnForm.getBlockCache("blockCache_" + i));
				hm.put("ttl", addColumnForm.getTtl("ttl_" + i));
				hm.put("bloomFilter", addColumnForm.getBloomFilter("bloomFilter_" + i));
				
				columnFamily.add(hm);
			}
		}
		
		try {
			to.addColumnFamily(master,tableName, columnFamily);
			return new ActionForward("/viewTableDetail.do?tableName=" + tableName + "&type=viewDescriptor");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return null;
		}
	}
}