/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.hadoop.hbase.MasterNotRunningException;
import org.apache.hadoop.hbase.ZooKeeperConnectionException;
import org.apache.hadoop.hbase.master.HMaster;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ocrabaseadmin.operation.authorityOperation;
import com.ocrabaseadmin.struts.form.AddUserForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-04-2011
 * 
 * XDoclet definition:
 * @struts.action path="/addUser" name="addUserForm" input="/authorityManagement.jsp" scope="request" validate="true"
 */
public class AddUserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddUserForm addUserForm = (AddUserForm) form;// TODO Auto-generated method stub
		
		String username = addUserForm.getUsername();
		String password = addUserForm.getPassword();
		String confirmPassword = addUserForm.getConfirmPassword();
		
		HMaster master = (HMaster)getServlet().getServletContext().getAttribute(HMaster.MASTER);
		
		if(!password.equals(confirmPassword)) {
			try {
				PrintWriter out = response.getWriter();
				
				out.println("<script>");
				out.println("alert(\"Confirm Password Error.\");");
				out.println("window.location=\"/userManagement.do?type=user\";");
				out.println("</script>");
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			return null;
		}
		else {
			authorityOperation ao = new authorityOperation();
			
			try {
				if(ao.addUser(master,username,password) == true) {
					return mapping.findForward("success");
				}
				else {
					try {
						PrintWriter out = response.getWriter();
						
						out.println("<script>");
						out.println("alert(\"Username Already Existed.\");");
						out.println("window.location=\"/userManagement.do?type=user\";");
						out.println("</script>");
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					
					return null;
				}
			} catch (MasterNotRunningException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				try {
					PrintWriter out = response.getWriter();
					
					out.println("<script>");
					out.println("alert(\"Username Already Existed.\");");
					out.println("window.location=\"/userManagement.do?type=user\";");
					out.println("</script>");
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				
				return null;
			} catch (ZooKeeperConnectionException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				try {
					PrintWriter out = response.getWriter();
					
					out.println("<script>");
					out.println("alert(\"Username Already Existed.\");");
					out.println("window.location=\"/userManagement.do?type=user\";");
					out.println("</script>");
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				
				return null;
			}
		}
	}
}