/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.hadoop.hbase.master.HMaster;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ocrabaseadmin.operation.authorityOperation;

/** 
 * MyEclipse Struts
 * Creation date: 09-04-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ChangeAuthorityAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		HMaster master = (HMaster)getServlet().getServletContext().getAttribute(HMaster.MASTER);
		String tablename = request.getParameter("tablename");
		String user = request.getParameter("user");
		String group = request.getParameter("group");
		String authority = request.getParameter("authority");
		
		authorityOperation ao  = new authorityOperation();
		
		try {
			ao.changeAuthority(master,tablename,user,group,authority);
			
			PrintWriter out = response.getWriter();
			out.println("<script>");
			out.println("alert(\"Change Successfully.\");");
			out.println("<script>");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		return mapping.findForward("success");
	}
}