/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.hbase.MasterNotRunningException;
import org.apache.hadoop.hbase.ZooKeeperConnectionException;
import org.apache.hadoop.hbase.master.HMaster;
import org.apache.hadoop.hbase.util.Bytes;
import org.apache.hadoop.security.UserValidator;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ocrabaseadmin.operation.authorityOperation;
import com.ocrabaseadmin.struts.form.ChangePasswordForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-04-2011
 * 
 * XDoclet definition:
 * @struts.action path="/changePassword" name="changePasswordForm" input="/userProfile.jsp" scope="request" validate="true"
 */
public class ChangePasswordAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ChangePasswordForm changePasswordForm = (ChangePasswordForm) form;// TODO Auto-generated method stub
		
		String username = (String)request.getSession().getAttribute("username");
		String userType = (String)request.getSession().getAttribute("usertype");
		String password = changePasswordForm.getPassword();
		String newPassword = changePasswordForm.getNewPassword();
		String confirmPassword = changePasswordForm.getConfirmPassword();
		
		HMaster master = (HMaster)getServlet().getServletContext().getAttribute(HMaster.MASTER);
		Configuration conf = master.getConfiguration();
		
		PrintWriter out = null;
		
		try {
			out = response.getWriter();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		if(!newPassword.equals(confirmPassword)) {
			out.println("<script>");
			out.println("alert(\"Please Confirm Your New Password.\");");
			out.println("window.location=\"/userProfile.jsp\";");
			out.println("</script>");
			
			return null;
		}
		else {
			if(userType.equals("user")) {
				UserValidator uv = null;
				try {
					uv = new UserValidator(conf);
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				
				if(uv.validateUser(Bytes.toBytes(username), Bytes.toBytes(password)) == false) {
					out.println("<script>");
					out.println("alert(\"Wrong Password.\");");
					out.println("window.location=\"/userProfile.jsp\";");
					out.println("</script>");
					
					return null;
				}
				else {
					authorityOperation ao = new authorityOperation();
					try {
						ao.changeUserPassword(master, username, newPassword);
					} catch (MasterNotRunningException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					} catch (ZooKeeperConnectionException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					
					out.println("<script>");
					out.println("alert(\"Change Password Successfully.\");");
					out.println("window.location=\"/userProfile.jsp\";");
					out.println("</script>");
					
					return null;
				}
			}
			else {
				String adminUsername = conf.get("hbase.client.user");
				String adminPassword = conf.get("hbase.client.passwd");
				
				if(username.equals(adminUsername) && password.equals(adminPassword)) {
					authorityOperation ao = new authorityOperation();
					ao.changeAdminPassword(master, username, newPassword);
					
					out.println("<script>");
					out.println("alert(\"Change Password Successfully.\");");
					out.println("window.location=\"/userProfile.jsp\";");
					out.println("</script>");
					
					return null;
				}
				else {
					out.println("<script>");
					out.println("alert(\"Wrong Password.\");");
					out.println("window.location=\"/userProfile.jsp\";");
					out.println("</script>");
					
					return null;
				}
			}
		}
	}
}