/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.action;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.hadoop.hbase.MasterNotRunningException;
import org.apache.hadoop.hbase.ZooKeeperConnectionException;
import org.apache.hadoop.hbase.master.HMaster;
import org.apache.hadoop.security.ACLField;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ocrabaseadmin.operation.authorityOperation;

/** 
 * MyEclipse Struts
 * Creation date: 09-04-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetAuthorityInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		HMaster master = (HMaster)getServlet().getServletContext().getAttribute(HMaster.MASTER);
		
		authorityOperation ao = new authorityOperation();
		
		String userType = (String)request.getSession().getAttribute("usertype");
		boolean ifAdmin = userType.equals("admin");
		String username = (String)request.getSession().getAttribute("username");
		
		if(ifAdmin) {
			try {
				Map<byte[],ACLField> tables = ao.getAllTable(master);
				
				request.setAttribute("tables", tables);
			} catch (MasterNotRunningException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (ZooKeeperConnectionException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		else {
			try {
				Map<byte[],ACLField> tables = ao.getUserTable(master,username);
				
				request.setAttribute("tables", tables);
			} catch (MasterNotRunningException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (ZooKeeperConnectionException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		return mapping.findForward("success");
	}
}