/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.action;

import ict.ocrabase.main.java.client.webinterface.ImportAdmin;
import ict.ocrabase.main.java.client.webinterface.TaskManager;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.hbase.MasterNotRunningException;
import org.apache.hadoop.hbase.ZooKeeperConnectionException;
import org.apache.hadoop.hbase.master.HMaster;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ocrabaseadmin.operation.authorityOperation;
import com.ocrabaseadmin.struts.form.ImportDataForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-23-2011
 * 
 * XDoclet definition:
 * @struts.action path="/importData" name="importDataForm" input="/importData.jsp" scope="request" validate="true"
 */
public class ImportDataAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ImportDataForm importDataForm = (ImportDataForm) form;// TODO Auto-generated method stub
		
		final String tableName = (String)importDataForm.getTableName();
		final String sourceDirectory = (String)importDataForm.getSourceDirectory();
		String separator = (String)importDataForm.getSeparator();
		final String isBulkload = (String)importDataForm.getIsBulkload();
		String isRowKey = (String)importDataForm.getIsRowKey();
		String ifOrdered = (String)importDataForm.getIfOrdered();
		String rowKeyLength = (String)importDataForm.getRowKeyLength();
		
		//authority
		HMaster master = (HMaster)getServlet().getServletContext().getAttribute(HMaster.MASTER);
		
		Configuration conf = master.getConfiguration();
		boolean security = conf.getBoolean("hbase.server.security",false);
		if(security) {
			String username = (String)request.getSession().getAttribute("username");
			String usertype = (String)request.getSession().getAttribute("usertype");
			
			if(usertype.equals("user")) {
				authorityOperation ao = new authorityOperation();
				try {
					if(!ao.validateUserOperation(master, tableName, ao.getUserTypeForTable(master, username, tableName), true)) {
						PrintWriter out = response.getWriter();
						out.println("<script>");
						out.println("alert(\"You Have No Access.\");");
						out.println("window.location=\"/viewTableDetail.do?tableName=" + tableName + "&type=importData\";");
						out.println("</script>");
						
						return null;
					}
				} catch (MasterNotRunningException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ZooKeeperConnectionException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}
		
		if(TaskManager.isActive(tableName)) {
			PrintWriter out;
			try {
				out = response.getWriter();
				
				out.println("<script>");
				out.println("alert(\"The Table is Locked.\");");
				out.println("window.location=\"/viewTableList.do\";");
				out.println("</script>");
				
				return null;
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		//authority
		
		final ArrayList<String> columnName = new ArrayList<String>();
		
		for(int i = 1; ;i++) {
			if(importDataForm.getColumnFamily("columnFamily_" + i) == null) {
				break;
			}
			else {
				columnName.add((String)importDataForm.getColumnFamily("columnFamily_" + i) + ":" + (String)importDataForm.getColumnName("columnName_" + i));
			}
		}
		
		final byte sep;
		if(separator.equals("tab")) {
			sep = (byte)'\t';
		}
		else if(separator.equals("space")) {
			sep = (byte)' ';
		}
		else {
			sep = (byte)',';
		}
		
		String tempType = new String();
		if(isRowKey.equals("true")) {
			tempType = "i " + rowKeyLength;
		}
		else if(ifOrdered.equals("true")) {
			tempType = "iu";
		}
		else {
			tempType = "u";
		}
		final String type = tempType;
		
		Thread t = new Thread() {
			public void run() {
				try {
					ImportAdmin.importData(tableName, columnName, sourceDirectory, sep, Boolean.parseBoolean(isBulkload), type);
				} catch (NumberFormatException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		};
		
		t.start();
		
		return mapping.findForward("success");
	}
}