/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ocrabaseadmin.operation.dataOperation;

/** 
 * MyEclipse Struts
 * Creation date: 09-16-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/queryDataResult.jsp"
 */
public class QueryDataResultAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		dataOperation dao = (dataOperation) request.getSession().getAttribute("QUERYDATA");
		int page = Integer.parseInt(request.getParameter("page"));
		
		request.setAttribute("viewResult", dao.getQueryResult(page * 20, page * 20 + 19));
		request.setAttribute("page", Integer.toString(page));
		
		return mapping.findForward("success");
	}
}