/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.hadoop.hbase.MasterNotRunningException;
import org.apache.hadoop.hbase.ZooKeeperConnectionException;
import org.apache.hadoop.hbase.master.HMaster;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ocrabaseadmin.operation.dataOperation;
import com.ocrabaseadmin.struts.form.QueryDataForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-16-2011
 * 
 * XDoclet definition:
 * @struts.action path="/queryData" name="queryDataForm" input="/queryData.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/queryDataResult.jsp"
 */
public class QueryDataAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		QueryDataForm queryDataForm = (QueryDataForm) form;// TODO Auto-generated method stub
		
		HMaster master = (HMaster)getServlet().getServletContext().getAttribute(HMaster.MASTER);
		
		String query = queryDataForm.getQuery();
		query = query.replaceAll("&lt;","<");
		query = query.replaceAll("&gt;",">");
		query = query.replaceAll("&amp;","&");
		query = query.replaceAll("&quot;","\"");
		query = query.replaceAll("&nbsp;"," ");
		query = query.replaceAll("&apos;","'");
		
		dataOperation dao = new dataOperation();
		
		try {
			dao.queryData(master, query);
		} catch (MasterNotRunningException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ZooKeeperConnectionException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		request.getSession().setAttribute("QUERYDATA", dao);
		
		return mapping.findForward("success");
	}
}