/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.action;

import ict.ocrabase.main.java.client.webinterface.ImportAdmin;

import java.util.LinkedList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ocrabaseadmin.struts.form.RowKeyCheckForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-23-2011
 * 
 * XDoclet definition:
 * @struts.action path="/rowKeyCheck" name="rowKeyCheckForm" input="/importData.jsp" scope="request" validate="true"
 */
public class RowKeyCheckAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RowKeyCheckForm rowKeyCheckForm = (RowKeyCheckForm) form;// TODO Auto-generated method stub

		String sourceDirectory = (String)rowKeyCheckForm.getSourceDirectory();
		String rowKeyLength = (String)rowKeyCheckForm.getRowKeyLength();
		
		List<String> columnFamily = new LinkedList<String>();
		List<String> columnName = new LinkedList<String>();
		
		for(int i = 1; ;i++) {
			if(rowKeyCheckForm.getColumnFamily("columnFamily_" + i) == null) {
				break;
			}
			else {
				columnFamily.add((String)rowKeyCheckForm.getColumnFamily("columnFamily_" + i));
				columnName.add((String)rowKeyCheckForm.getColumnName("columnName_" + i));
			}
		}
		
		//Row Key Check
		int isSuitable = ImportAdmin.isSuitable(sourceDirectory, Integer.parseInt(rowKeyLength));
		if( isSuitable == 0) {
			request.setAttribute("checkResult", "Suitable");
		}
		else {
			request.setAttribute("checkResult", "The Length of Rowkey is " + isSuitable + " at least.");
		}
		
		return mapping.findForward("success");
	}
}