/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import ict.ocrabase.main.java.regionserver.statclient.SQLStatus;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ocrabaseadmin.operation.dataOperation;
import com.ocrabaseadmin.struts.form.TestStatisticsQueryForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2011
 * 
 * XDoclet definition:
 * @struts.action path="/testStatisticsQuery" name="testStatisticsQueryForm" input="/performanceTest.jsp" scope="request" validate="true"
 */
public class TestStatisticsQueryAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TestStatisticsQueryForm testStatisticsQueryForm = (TestStatisticsQueryForm) form;// TODO Auto-generated method stub
		
		String query = testStatisticsQueryForm.getQuery();
		
		query = query.replaceAll("&lt;","<");
		query = query.replaceAll("&gt;",">");
		query = query.replaceAll("&amp;","&");
		query = query.replaceAll("&quot;","\"");
		query = query.replaceAll("&nbsp;"," ");
		query = query.replaceAll("&apos;","'");
		
		if((query.indexOf("count") == -1) && (query.indexOf("avg") == -1) && (query.indexOf("sum") == -1) && (query.indexOf("group") == -1) && (query.indexOf("order") == -1) && (query.indexOf("limit") == -1)) {
			String tempPage = (String)request.getParameter("page");
			dataOperation dao = (dataOperation)request.getSession().getAttribute("QUERYRESULT");
			if(tempPage == null) {
				dao = new dataOperation();
				try {
					dao.createQuery(query);
					request.getSession().setAttribute("QUERYRESULT",dao);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
					try {
						PrintWriter out = response.getWriter();
						out.println("<script>");
						out.println("alert(\"Invalid Query.\");");
						out.println("</script>");
						
						return null;
					} catch (IOException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
				}
				tempPage = "0";
			}
			int page = Integer.parseInt(tempPage);
			request.setAttribute("viewResult", dao.getQueryResult(page * 20, page * 20 + 19));
			request.setAttribute("page", Integer.toString(page));
			
			return mapping.findForward("query");
		}
		else {
			try {
				SQLStatus querytd = new SQLStatus(query);
				querytd.start();
				request.getSession().setAttribute("QUERYTD", querytd);
				
				System.out.println(query);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				try {
					PrintWriter out = response.getWriter();
					
					out.println(e.toString());
					out.println("<script type=\"text/javascript\">");
					out.println("alert(\"Error , query  setup error,please check carefully!\");");
					out.println("</script>");
					
					return null;
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
			return mapping.findForward("statistics");
		}
	}
}