/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.action;

import ict.ocrabase.main.java.client.bulkload.BulkLoad;
import ict.ocrabase.main.java.client.webinterface.ImportAdmin;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ocrabaseadmin.struts.form.TestBulkLoadForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2011
 * 
 * XDoclet definition:
 * @struts.action path="/testBulkLoad" name="testBulkLoadForm" input="/performanceTest.jsp" scope="request" validate="true"
 */
public class TestBulkLoadAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TestBulkLoadForm testBulkLoadForm = (TestBulkLoadForm) form;// TODO Auto-generated method stub
		
		final String tableName = testBulkLoadForm.getTableName();
		final String dataRes = testBulkLoadForm.getDataRes();
		
		try {
			final BulkLoad bl = ImportAdmin.testImportDataInit(tableName, dataRes);
			
			Thread t = new Thread() {
				public void run() {
					try {
						bl.run();
					} catch (IOException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
					
					while (bl.isComplete() == false) {
						try {
							Thread.sleep(1000);
						} catch (InterruptedException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					}
				}
			};
			
			t.start();
			
			request.getSession().setAttribute("BULKLOAD", bl);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			
			try {
				PrintWriter out = response.getWriter();
				
				out.println("<script>");
				out.println("alert(\"" + e + "\");");
				out.println("</script>");
				
				return null;
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
		
		return mapping.findForward("success");
	}
}