/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.form;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2011
 * 
 * XDoclet definition:
 * @struts.form name="createTableForm"
 */
public class CreateTableForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private HashMap<String,Object> familyName = new HashMap<String,Object>();
	private HashMap<String,Object> versions = new HashMap<String,Object>();
	private HashMap<String,Object> compression = new HashMap<String,Object>();
	private HashMap<String,Object> inMemory = new HashMap<String,Object>();
	private HashMap<String,Object> blockCache = new HashMap<String,Object>();
	private HashMap<String,Object> ttl = new HashMap<String,Object>();
	private HashMap<String,Object> bloomFilter = new HashMap<String,Object>();
	
	private String newTableName = new String();
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Object getFamilyName(String key) {
		return familyName.get(key);
	}

	public void setFamilyName(String key,Object value) {
		familyName.put(key,value);
	}

	public Object getVersions(String key) {
		return versions.get(key);
	}

	public void setVersions(String key,Object value) {
		versions.put(key, value);
	}

	public Object getCompression(String key) {
		return compression.get(key);
	}

	public void setCompression(String key,Object value) {
		compression.put(key, value);
	}

	public Object getInMemory(String key) {
		return inMemory.get(key);
	}

	public void setInMemory(String key,Object value) {
		inMemory.put(key, value);
	}

	public Object getBlockCache(String key) {
		return blockCache.get(key);
	}

	public void setBlockCache(String key,Object value) {
		blockCache.put(key, value);
	}

	public Object getTtl(String key) {
		return ttl.get(key);
	}

	public void setTtl(String key,Object value) {
		ttl.put(key, value);
	}

	public Object getBloomFilter(String key) {
		return bloomFilter.get(key);
	}

	public void setBloomFilter(String key,Object value) {
		bloomFilter.put(key, value);
	}

	public String getNewTableName() {
		return newTableName;
	}

	public void setNewTableName(String newTableName) {
		this.newTableName = newTableName;
	}
}