/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.form;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-19-2011
 * 
 * XDoclet definition:
 * @struts.form name="editIndexForm"
 */
public class EditIndexForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	private HashMap<String,Object> columnFamily = new HashMap<String,Object>();
	private HashMap<String,Object> qualifier = new HashMap<String,Object>();
	private HashMap<String,Object> indexType = new HashMap<String,Object>();
	
	String newTableName = new String();
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Object getColumnFamily(String key) {
		return columnFamily.get(key);
	}

	public void setColumnFamily(String key, Object value) {
		columnFamily.put(key, value);
	}

	public Object getQualifier(String key) {
		return qualifier.get(key);
	}

	public void setQualifier(String key, Object value) {
		qualifier.put(key, value);
	}

	public Object getIndexType(String key) {
		return indexType.get(key);
	}

	public void setIndexType(String key, Object value) {
		indexType.put(key, value);
	}

	public String getNewTableName() {
		return newTableName;
	}

	public void setNewTableName(String newTableName) {
		this.newTableName = newTableName;
	}
}