/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.form;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-23-2011
 * 
 * XDoclet definition:
 * @struts.form name="importDataForm"
 */
public class ImportDataForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	private String tableName = new String();
	private String sourceDirectory = new String();
	private String separator = new String();
	private String isBulkload = new String();
	private String isRowKey = new String();
	private String ifOrdered = new String();
	private String rowKeyLength = new String();
	
	private HashMap<String,Object> columnFamily = new HashMap<String,Object>();
	private HashMap<String,Object> columnName = new HashMap<String,Object>();
		
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getSourceDirectory() {
		return sourceDirectory;
	}

	public void setSourceDirectory(String sourceDirectory) {
		this.sourceDirectory = sourceDirectory;
	}

	public String getSeparator() {
		return separator;
	}

	public void setSeparator(String separator) {
		this.separator = separator;
	}

	public String getIsBulkload() {
		return isBulkload;
	}

	public void setIsBulkload(String isBulkload) {
		this.isBulkload = isBulkload;
	}

	public String getIsRowKey() {
		return isRowKey;
	}

	public void setIsRowKey(String isRowKey) {
		this.isRowKey = isRowKey;
	}

	public String getIfOrdered() {
		return ifOrdered;
	}

	public void setIfOrdered(String ifOrdered) {
		this.ifOrdered = ifOrdered;
	}

	public String getRowKeyLength() {
		return rowKeyLength;
	}

	public void setRowKeyLength(String rowKeyLength) {
		this.rowKeyLength = rowKeyLength;
	}

	public Object getColumnFamily(String key) {
		return columnFamily.get(key);
	}

	public void setColumnFamily(String key, Object value) {
		columnFamily.put(key, value);
	}

	public Object getColumnName(String key) {
		return columnName.get(key);
	}

	public void setColumnName(String key, Object value) {
		columnName.put(key, value);
	}
}