/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.form;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-17-2011
 * 
 * XDoclet definition:
 * @struts.form name="insertDataForm"
 */
public class InsertDataForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	
	private String rowKey = new String();
	private String tableName = new String();
	
	private HashMap<String,Object> familyName = new HashMap<String,Object>();
	private HashMap<String,Object> qualifier = new HashMap<String,Object>();
	private HashMap<String,Object> values = new HashMap<String,Object>();
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Object getFamilyName(String key) {
		return familyName.get(key);
	}

	public void setFamilyName(String key, Object value) {
		familyName.put(key, value);
	}

	public Object getQualifier(String key) {
		return qualifier.get(key);
	}

	public void setQualifier(String key, Object value) {
		qualifier.put(key, value);
	}

	public Object getValues(String key) {
		return values.get(key);
	}

	public void setValues(String key, Object value) {
		values.put(key, value);
	}

	public String getRowKey() {
		return rowKey;
	}

	public void setRowKey(String rowKey) {
		this.rowKey = rowKey;
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
}