/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2011
 * 
 * XDoclet definition:
 * @struts.form name="testDataGenerationForm"
 */
public class TestDataGenerationForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** dataSize property */
	private String dataSize;

	/** threadNumber property */
	private String threadNumber;

	/** dataSet property */
	private String dataSet;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the dataSize.
	 * @return String
	 */
	public String getDataSize() {
		return dataSize;
	}

	/** 
	 * Set the dataSize.
	 * @param dataSize The dataSize to set
	 */
	public void setDataSize(String dataSize) {
		this.dataSize = dataSize;
	}

	/** 
	 * Returns the threadNumber.
	 * @return String
	 */
	public String getThreadNumber() {
		return threadNumber;
	}

	/** 
	 * Set the threadNumber.
	 * @param threadNumber The threadNumber to set
	 */
	public void setThreadNumber(String threadNumber) {
		this.threadNumber = threadNumber;
	}

	/** 
	 * Returns the dataSet.
	 * @return String
	 */
	public String getDataSet() {
		return dataSet;
	}

	/** 
	 * Set the dataSet.
	 * @param dataSet The dataSet to set
	 */
	public void setDataSet(String dataSet) {
		this.dataSet = dataSet;
	}
}