/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-03-2011
 * 
 * XDoclet definition:
 * @struts.form name="testIndexImportForm"
 */
public class TestIndexImportForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** hbaseHome property */
	private String hbaseHome;

	/** indexArray property */
	private String indexArray;

	/** clientsPerHost property */
	private String clientsPerHost;

	/** threadsPerClient property */
	private String threadsPerClient;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the hbaseHome.
	 * @return String
	 */
	public String getHbaseHome() {
		return hbaseHome;
	}

	/** 
	 * Set the hbaseHome.
	 * @param hbaseHome The hbaseHome to set
	 */
	public void setHbaseHome(String hbaseHome) {
		this.hbaseHome = hbaseHome;
	}

	/** 
	 * Returns the indexArray.
	 * @return String
	 */
	public String getIndexArray() {
		return indexArray;
	}

	/** 
	 * Set the indexArray.
	 * @param indexArray The indexArray to set
	 */
	public void setIndexArray(String indexArray) {
		this.indexArray = indexArray;
	}

	/** 
	 * Returns the clientsPerHost.
	 * @return String
	 */
	public String getClientsPerHost() {
		return clientsPerHost;
	}

	/** 
	 * Set the clientsPerHost.
	 * @param clientsPerHost The clientsPerHost to set
	 */
	public void setClientsPerHost(String clientsPerHost) {
		this.clientsPerHost = clientsPerHost;
	}

	/** 
	 * Returns the threadsPerClient.
	 * @return String
	 */
	public String getThreadsPerClient() {
		return threadsPerClient;
	}

	/** 
	 * Set the threadsPerClient.
	 * @param threadsPerClient The threadsPerClient to set
	 */
	public void setThreadsPerClient(String threadsPerClient) {
		this.threadsPerClient = threadsPerClient;
	}
}