/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ocrabaseadmin.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2011
 * 
 * XDoclet definition:
 * @struts.form name="testBulkLoadForm"
 */
public class TestBulkLoadForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** tableName property */
	private String tableName;

	/** dataSet property */
	private String dataRes;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the hbaseHome.
	 * @return String
	 */
	public String getTableName() {
		return tableName;
	}

	/** 
	 * Set the hbaseHome.
	 * @param hbaseHome The hbaseHome to set
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/** 
	 * Returns the dataRes.
	 * @return String
	 */
	public String getDataRes() {
		return dataRes;
	}

	/** 
	 * Set the dataSet.
	 * @param dataSet The dataSet to set
	 */
	public void setDataRes(String dataRes) {
		this.dataRes = dataRes;
	}
}